---
apiVersion: v1
kind: Secret
metadata:
  name: iapteca-secret
  namespace: iapteca
type: Opaque
data:
  MONGODB_PASSWORD: bW9uZ29fcGFzc3dvcmQ=  # mongopassword
  MONGODB_USERNAME: bW9uZ29fdXNlcg==  # mongouser
