---
apiVersion: v1
kind: Service
metadata:
  name: product-catalog
  namespace: iapteca
  labels:
    app: product-catalog
spec:
  selector:
    app: product-catalog
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP
